[program:portfolio-scheduler]
command=php /home/joalacom/public_html/artisan schedule:run
directory=/home/joalacom/public_html
stdout_logfile=/home/joalacom/public_html/storage/logs/scheduler.log
stderr_logfile=/home/joalacom/public_html/storage/logs/scheduler_error.log
redirect_stderr=true
autorestart=true
startsecs=0
user=joalacom
priority=999

[program:portfolio-queue]
command=php /home/joalacom/public_html/artisan queue:work --sleep=3 --tries=3
directory=/home/joalacom/public_html
stdout_logfile=/home/joalacom/public_html/storage/logs/queue.log
stderr_logfile=/home/joalacom/public_html/storage/logs/queue_error.log
redirect_stderr=true
autorestart=true
startsecs=0
user=joalacom
priority=998
stopwaitsecs=3600